import type { EmbedGameMeta } from '@/types/game';

/**
 * Third-party embed catalog. Provider-agnostic by design — each entry carries
 * its own `provider` and `embedUrl`, so swapping providers (or mixing them) is
 * a matter of editing single rows.
 *
 * Current seed: 20 verified GameDistribution titles. Each embed URL was checked
 * on 2026-05-15 — see docs/plans/2026-05-15-embed-games-design.md.
 */
const gd = (id: string) => `https://html5.gamedistribution.com/${id}/`;

export const EMBED_GAMES: readonly EmbedGameMeta[] = [
  // ── Arcade ─────────────────────────────────────────────────────────────
  {
    kind: 'embed',
    slug: 'moto-x3m',
    title: 'Moto X3M',
    description: 'Race against the clock through wild stunt tracks.',
    longDescription:
      'A bike racing game with 25 challenging levels. Strap on your helmet, grab some airtime over obstacles, and beat the clock on amazing off-road circuits.',
    thumbnail: '/assets/thumbnails/embed-moto-x3m.jpg',
    category: 'racing',
    difficulty: 'medium',
    controls: 'Arrow keys',
    color: '#facc15',
    keywords: ['moto x3m', 'bike racing', 'stunt game', 'motorcycle'],
    status: 'live',
    provider: 'gamedistribution',
    embedUrl: gd('5b0abd4c0faa4f5eb190a9a16d5a1b4c'),
  },
  {
    kind: 'embed',
    slug: 'hill-climb-racing-2',
    title: 'Hill Climb Racing 2',
    description: 'Climb hills, collect coins, upgrade your ride.',
    longDescription:
      'Control your car or bike to climb hills with realistic physics. Face unique uphill and downhill environments, earn bonuses from tricks, and collect coins to upgrade.',
    thumbnail: '/assets/thumbnails/embed-hill-climb-racing-2.jpg',
    category: 'racing',
    difficulty: 'easy',
    controls: 'Arrow keys',
    color: '#84cc16',
    keywords: ['hill climb', 'physics racing', 'driving game'],
    status: 'live',
    provider: 'gamedistribution',
    embedUrl: gd('ddcba9beafaf409ab581385023761cde'),
  },
  {
    kind: 'embed',
    slug: 'helix-jump',
    title: 'Helix Jump',
    description: 'Guide a bouncing ball down a twisting tower.',
    longDescription:
      'Helix Jump has simple, addictive mechanics. Guide a bouncing ball continuously down a series of circular platforms, falling through cracks while avoiding the forbidden zones.',
    thumbnail: '/assets/thumbnails/embed-helix-jump.jpg',
    category: 'arcade',
    difficulty: 'easy',
    controls: 'Mouse / Touch drag',
    color: '#f472b6',
    keywords: ['helix jump', 'ball game', 'tower descent'],
    status: 'live',
    provider: 'gamedistribution',
    embedUrl: gd('544cf55c6ad44a3299099e813f7f5a9d'),
  },
  {
    kind: 'embed',
    slug: 'stickman-death-run',
    title: 'Stickman Death Run',
    description: 'Run, jump, and dodge through deadly traps.',
    longDescription:
      "Everyone's favorite stickman is now on a death run in the pixel world. Help him run through obstacles and survive as long as you can.",
    thumbnail: '/assets/thumbnails/embed-stickman-death-run.jpg',
    category: 'arcade',
    difficulty: 'medium',
    controls: 'Arrow keys / Touch',
    color: '#ef4444',
    keywords: ['stickman', 'runner', 'platformer'],
    status: 'live',
    provider: 'gamedistribution',
    embedUrl: gd('df7da06701574ce9acc39d3355b44522'),
  },
  {
    kind: 'embed',
    slug: 'stick-run',
    title: 'Stick Run',
    description: 'Run through tunnels and outsmart traps.',
    longDescription:
      'A group of stickmen get lost in tunnels floating around the world. Run through varied environments — cities, deserts, mountains — and avoid every trap.',
    thumbnail: '/assets/thumbnails/embed-stick-run.jpg',
    category: 'arcade',
    difficulty: 'easy',
    controls: 'Arrow keys / Touch',
    color: '#fb923c',
    keywords: ['stick run', 'runner', 'stickman'],
    status: 'live',
    provider: 'gamedistribution',
    embedUrl: gd('8ade51370cd7424ea0a67eb7452abd82'),
  },
  {
    kind: 'embed',
    slug: 'stickman-school-run',
    title: 'Stickman School Run',
    description: 'Skip homework, save your girlfriend.',
    longDescription:
      "Take control of a little wire man who's trying to run away from his homework and save his girlfriend. Dodge teachers and obstacles along the way.",
    thumbnail: '/assets/thumbnails/embed-stickman-school-run.jpg',
    category: 'arcade',
    difficulty: 'easy',
    controls: 'Arrow keys / Touch',
    color: '#f59e0b',
    keywords: ['stickman', 'school run', 'runner'],
    status: 'live',
    provider: 'gamedistribution',
    embedUrl: gd('61f143e520804499919733156c98d169'),
  },
  {
    kind: 'embed',
    slug: 'stick-duel-battle',
    title: 'Stick Duel Battle',
    description: 'Fight with realistic weapons and physics.',
    longDescription:
      'A funny and crazy stickman battle game. Fight with realistic weapons and physics on many maps. Single player or local versus.',
    thumbnail: '/assets/thumbnails/embed-stick-duel-battle.jpg',
    category: 'arcade',
    difficulty: 'medium',
    controls: 'Keyboard',
    color: '#dc2626',
    keywords: ['stick duel', 'fighting', 'physics'],
    status: 'live',
    provider: 'gamedistribution',
    embedUrl: gd('1d7959f081b4453498ee9916b693988c'),
  },

  // ── Puzzle ─────────────────────────────────────────────────────────────
  {
    kind: 'embed',
    slug: 'bubble-shooter-original',
    title: 'Bubble Shooter',
    description: 'Match three bubbles to clear the board.',
    longDescription:
      'The classic bubble shooter. Aim and shoot bubbles, match three of the same color to pop them. Clear the board to advance.',
    thumbnail: '/assets/thumbnails/embed-bubble-shooter-original.jpg',
    category: 'puzzle',
    difficulty: 'easy',
    controls: 'Mouse / Touch',
    color: '#38bdf8',
    keywords: ['bubble shooter', 'match three', 'puzzle'],
    status: 'live',
    provider: 'gamedistribution',
    embedUrl: gd('d07a3f925bf345bcbddf18abad7d9f19'),
  },
  {
    kind: 'embed',
    slug: 'bubble-shooter-hd',
    title: 'Bubble Shooter HD',
    description: 'High-def take on the classic bubble shooter.',
    longDescription:
      'Remove all bubbles from the board, scoring as many points as possible. Match two or more bubbles of the same color to pop them.',
    thumbnail: '/assets/thumbnails/embed-bubble-shooter-hd.jpg',
    category: 'puzzle',
    difficulty: 'easy',
    controls: 'Mouse / Touch',
    color: '#0ea5e9',
    keywords: ['bubble shooter', 'hd', 'puzzle'],
    status: 'live',
    provider: 'gamedistribution',
    embedUrl: gd('79a7db22af5f420eb9d56e28fffca87b'),
  },
  {
    kind: 'embed',
    slug: 'bubble-shooter-extreme',
    title: 'Bubble Shooter Extreme',
    description: 'Faster, harder bubble action.',
    longDescription:
      'An HTML5 version of the popular Bubble Shooter game with awesome HD graphics and faster pace.',
    thumbnail: '/assets/thumbnails/embed-bubble-shooter-extreme.jpg',
    category: 'puzzle',
    difficulty: 'medium',
    controls: 'Mouse / Touch',
    color: '#6366f1',
    keywords: ['bubble shooter', 'extreme', 'puzzle'],
    status: 'live',
    provider: 'gamedistribution',
    embedUrl: gd('c3f0f0c6731a4d908d978fb7906a0b17'),
  },
  {
    kind: 'embed',
    slug: 'jewel-pets-match',
    title: 'Jewel Pets Match',
    description: 'Match-3 with adorable pets.',
    longDescription:
      'A classic turn-based match-3 arcade game. Match happy pets in greater numbers to clear bigger portions of the board.',
    thumbnail: '/assets/thumbnails/embed-jewel-pets-match.jpg',
    category: 'puzzle',
    difficulty: 'easy',
    controls: 'Mouse / Touch',
    color: '#a855f7',
    keywords: ['match 3', 'jewel', 'pets'],
    status: 'live',
    provider: 'gamedistribution',
    embedUrl: gd('e8cd110d09fe4654821162dcd100b75d'),
  },
  {
    kind: 'embed',
    slug: 'jewel-solitaire-tripeaks',
    title: 'Jewel Solitaire TriPeaks',
    description: 'TriPeaks solitaire with a fantasy twist.',
    longDescription:
      'A magical solitaire adventure. Rebuild castles, conquer 200 levels, and master 12 variants from Klondike to Spider.',
    thumbnail: '/assets/thumbnails/embed-jewel-solitaire-tripeaks.jpg',
    category: 'puzzle',
    difficulty: 'medium',
    controls: 'Mouse / Touch',
    color: '#c084fc',
    keywords: ['solitaire', 'tripeaks', 'cards'],
    status: 'live',
    provider: 'gamedistribution',
    embedUrl: gd('89ab5569df404db3bb93f31a890c24e8'),
  },
  {
    kind: 'embed',
    slug: 'microsoft-solitaire-collection',
    title: 'Microsoft Solitaire Collection',
    description: 'Klondike, Spider, Freecell, Pyramid, TriPeaks.',
    longDescription:
      'The classic Microsoft Solitaire Collection. Five solitaire variants in one: Klondike, Spider, Freecell, Pyramid, and TriPeaks.',
    thumbnail: '/assets/thumbnails/embed-microsoft-solitaire-collection.jpg',
    category: 'puzzle',
    difficulty: 'easy',
    controls: 'Mouse / Touch',
    color: '#10b981',
    keywords: ['solitaire', 'microsoft', 'cards', 'klondike'],
    status: 'live',
    provider: 'gamedistribution',
    embedUrl: gd('6c5fd1a4f3544538a6bbdfdc1c7bd507'),
  },

  // ── Sports ─────────────────────────────────────────────────────────────
  {
    kind: 'embed',
    slug: 'basketball-stars',
    title: 'Basketball Stars',
    description: 'Two-player basketball — dunks and 3-pointers.',
    longDescription:
      'A cool 2-player basketball game by MadPuffers. Choose your team and enter a challenging tournament. Perform awesome dunks and three pointers to win.',
    thumbnail: '/assets/thumbnails/embed-basketball-stars.jpg',
    category: 'sports',
    difficulty: 'medium',
    controls: 'Keyboard (WASD + Arrow keys)',
    color: '#f97316',
    keywords: ['basketball', 'sports', 'two player'],
    status: 'live',
    provider: 'gamedistribution',
    embedUrl: gd('69d78d071f704fa183d75b4114ae40ec'),
  },
  {
    kind: 'embed',
    slug: 'basketball-legend',
    title: 'Basketball Legend',
    description: 'Master your shooting in solo or versus.',
    longDescription:
      'Become the basketball legend! Single player career mode or local multiplayer. Master dribbles, dunks, and clutch threes.',
    thumbnail: '/assets/thumbnails/embed-basketball-legend.jpg',
    category: 'sports',
    difficulty: 'medium',
    controls: 'Keyboard',
    color: '#ea580c',
    keywords: ['basketball', 'legend', 'sports'],
    status: 'live',
    provider: 'gamedistribution',
    embedUrl: gd('0d06f5faf6174728bb1cd2d8150daba4'),
  },
  {
    kind: 'embed',
    slug: 'super-soccer-stars',
    title: 'Super Soccer Stars',
    description: 'Score, defend, and beat the keeper.',
    longDescription:
      'A fast-paced arcade soccer game. Aim past the keeper, defend your goal, and rack up wins across tournaments.',
    thumbnail: '/assets/thumbnails/embed-super-soccer-stars.jpg',
    category: 'sports',
    difficulty: 'easy',
    controls: 'Mouse / Touch',
    color: '#16a34a',
    keywords: ['soccer', 'football', 'sports'],
    status: 'live',
    provider: 'gamedistribution',
    embedUrl: gd('f366faf74abd4d01a93fef0f2092f3cb'),
  },
  {
    kind: 'embed',
    slug: 'soccer-skills-runner',
    title: 'Soccer Skills Runner',
    description: 'Dribble past opponents in an endless run.',
    longDescription:
      'Run as far as you can without being tackled — swerve, jump, and duck past opponents. Collect power-ups and upgrade your player.',
    thumbnail: '/assets/thumbnails/embed-soccer-skills-runner.jpg',
    category: 'sports',
    difficulty: 'medium',
    controls: 'Arrow keys / Touch',
    color: '#22c55e',
    keywords: ['soccer', 'runner', 'sports'],
    status: 'live',
    provider: 'gamedistribution',
    embedUrl: gd('54df6d78ccde4de1b41acadb002f1722'),
  },
  {
    kind: 'embed',
    slug: '8-ball-pro',
    title: '8 Ball Pro',
    description: 'Pocket the 8 ball to win — pool perfected.',
    longDescription:
      'Test your 8 Ball Pool skills. Aim carefully, control your power, and pocket the 8 ball last to win each frame.',
    thumbnail: '/assets/thumbnails/embed-8-ball-pro.jpg',
    category: 'sports',
    difficulty: 'medium',
    controls: 'Mouse / Touch',
    color: '#1e40af',
    keywords: ['pool', '8 ball', 'billiards'],
    status: 'live',
    provider: 'gamedistribution',
    embedUrl: gd('20fa5406b00643128250478502fa5453'),
  },
  {
    kind: 'embed',
    slug: 'pool-8-ball',
    title: 'Pool 8 Ball',
    description: 'Classic pool — solo timer or shared device.',
    longDescription:
      'A modern pool game. Play alone on a timer or together on one device. Sink the colored balls before the 8.',
    thumbnail: '/assets/thumbnails/embed-pool-8-ball.jpg',
    category: 'sports',
    difficulty: 'easy',
    controls: 'Mouse / Touch',
    color: '#0c4a6e',
    keywords: ['pool', 'billiards', '8 ball'],
    status: 'live',
    provider: 'gamedistribution',
    embedUrl: gd('587cc8f8b84b484f9267a7ec1caa5328'),
  },

  // ── Racing ─────────────────────────────────────────────────────────────
  {
    kind: 'embed',
    slug: 'highway-traffic',
    title: 'Highway Traffic',
    description: 'Speed through traffic with multiple cars and modes.',
    longDescription:
      'A traffic game with diverse modes and car models — from classic sedans to modern sports cars. Four single-player modes, three weather options, smooth controls.',
    thumbnail: '/assets/thumbnails/embed-highway-traffic.jpg',
    category: 'racing',
    difficulty: 'medium',
    controls: 'Arrow keys / Touch',
    color: '#0891b2',
    keywords: ['highway', 'traffic', 'racing', 'cars'],
    status: 'live',
    provider: 'gamedistribution',
    embedUrl: gd('7c151f5e29eb40a591edfe1823e1d0ea'),
  },
] as const;
